-- ============================================================
-- 3DMP Service · 0112_login_guard.sql  (v100 — Итерация 3: безопасность входа)
-- Защита входа: счётчик неудачных попыток, временная блокировка, журнал попыток.
-- app_login теперь возвращает (..., ok boolean, message text).
-- Идемпотентно. Зависит от 0001..0111.
-- ============================================================

alter table public.app_users
  add column if not exists failed_attempts int not null default 0,
  add column if not exists locked_until timestamptz;

create table if not exists public.app_login_attempts (
  id         bigint generated by default as identity primary key,
  login      text,
  success    boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists app_login_attempts_idx on public.app_login_attempts (login, created_at desc);
alter table public.app_login_attempts enable row level security;

-- ---------- app_login с защитой ----------
drop function if exists public.app_login(text, text);
create or replace function public.app_login(p_login text, p_password text)
returns table (token uuid, user_id uuid, login text, full_name text, role text, ok boolean, message text)
language plpgsql security definer set search_path = public, extensions
as $$
#variable_conflict use_column
declare u public.app_users; tk uuid; maxf constant int := 5; lockwin constant interval := interval '15 minutes';
begin
  select * into u from public.app_users au where lower(au.login) = lower(trim(p_login)) and au.active limit 1;
  if u.id is null then
    insert into public.app_login_attempts (login, success) values (lower(trim(p_login)), false);
    return query select null::uuid, null::uuid, null::text, null::text, null::text, false, 'Неверный логин или пароль';
    return;
  end if;
  if u.locked_until is not null and u.locked_until > now() then
    insert into public.app_login_attempts (login, success) values (u.login, false);
    return query select null::uuid, u.id, u.login, u.full_name, u.role, false,
      'Вход временно заблокирован до ' || to_char(u.locked_until, 'DD.MM HH24:MI');
    return;
  end if;
  if u.password_hash <> extensions.crypt(p_password, u.password_hash) then
    update public.app_users
       set failed_attempts = u.failed_attempts + 1,
           locked_until = case when u.failed_attempts + 1 >= maxf then now() + lockwin else u.locked_until end
     where id = u.id;
    insert into public.app_login_attempts (login, success) values (u.login, false);
    if u.failed_attempts + 1 >= maxf then
      return query select null::uuid, u.id, u.login, u.full_name, u.role, false,
        'Превышено число попыток. Вход заблокирован на 15 минут.';
    else
      return query select null::uuid, u.id, u.login, u.full_name, u.role, false,
        'Неверный логин или пароль (попытка ' || (u.failed_attempts + 1)::text || ' из ' || maxf::text || ')';
    end if;
    return;
  end if;
  update public.app_users set last_login_at = now(), failed_attempts = 0, locked_until = null where id = u.id;
  insert into public.app_login_attempts (login, success) values (u.login, true);
  insert into public.app_events (user_id, login, action, detail) values (u.id, u.login, 'Вход', 'успешный вход');
  insert into public.app_sessions (user_id) values (u.id) returning app_sessions.token into tk;
  return query select tk, u.id, u.login, u.full_name, u.role, true, 'OK';
end $$;
grant execute on function public.app_login(text, text) to anon, authenticated;

-- ---------- Журнал попыток (только admin) ----------
create or replace function public.app_login_attempts_list(p_token uuid, p_limit integer default 100)
returns table (login text, success boolean, created_at timestamptz)
language plpgsql security definer set search_path = public
as $$
#variable_conflict use_column
declare urole text;
begin
  if not public.app_production_allowed(p_token) then raise exception 'Доступ запрещён'; end if;
  select s.urole into urole from public.app_session_user(p_token) s;
  if urole <> 'admin' then raise exception 'Недостаточно прав'; end if;
  return query select a.login, a.success, a.created_at from public.app_login_attempts a
    order by a.created_at desc limit greatest(1, least(coalesce(p_limit,100),500));
end $$;
grant execute on function public.app_login_attempts_list(uuid, integer) to anon, authenticated;

-- ---------- База знаний ----------
insert into public.app_knowledge (tenant_id, category, question, answer, tags)
select 'aaaaaaaa-0000-0000-0000-000000000001', v.category, v.question, v.answer, v.tags
from (values
  ('Безопасность','Защита входа: попытки и блокировка',
   'При 5 неверных входах подряд учётная запись блокируется на 15 минут (app_users.failed_attempts/locked_until). Все попытки пишутся в app_login_attempts; администратор платформы видит их через app_login_attempts_list. Успешный вход сбрасывает счётчик. Уведомление о блокировке показывается на форме входа.',
   'вход безопасность попытки блокировка rate limit 2fa app_login_attempts')
) as v(category,question,answer,tags)
where not exists (select 1 from public.app_knowledge where tenant_id='aaaaaaaa-0000-0000-0000-000000000001' and question='Защита входа: попытки и блокировка');
